version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
#    depends_on:
#      - db
#
#  db:
#    image: postgres:14.11
#    environment:
#      POSTGRES_DB: petprojectdjango
#      POSTGRES_USER: petdjangouser
#      POSTGRES_PASSWORD: 123456
#    ports:
#      - "5432:5432"

