services:
  postgres:
    image: postgres:latest
    container_name: postgres
#    environment:
#      POSTGRES_DB: <db_name>
#      POSTGRES_USER: <user_name>
#      POSTGRES_PASSWORD: <password>
    ports:
      - "5433:5432"

  django:
    build:
      context: .
    command: "python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    network_mode: host
